version: '3.7'

services:
  my-library-mysql:
    container_name: my-library-mysql-stage
    ports:
      - '33062:3306'

  my-library-php:
    container_name: my-library-php-stage
    environment:
      APP_ENV: prod
      APP_VERSION: prod
      DATABASE_URL: mysql://root:@my-library-mysql:3306/my-library_stage

  my-library-nginx:
    container_name: my-library-nginx-stage
    ports:
      - '8082:80'
